### ISSUE TITLE
Crashes documenting Intl

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dartdoc#397]
Tried this on the Intl package. Got the following.

parsing /Users/alanknight/intl/lib/message_lookup_by_library.dart...
			parsing /Users/alanknight/intl/lib/number_symbols.dart...
			parsing /Users/alanknight/intl/lib/number_symbols_data.dart...

			Parsed 13 libraries in 5.6 seconds.

			generating docs/index.html
			Unhandled exception:
			Uncaught Error: Unknown type PrefixElementImpl
			Stack Trace:
			#0      ModelElement.ModelElement.from (package:dartdoc/src/model.dart:97)
			#1      ModelElement.resolveReferences._getMatchingLink (package:dartdoc/src/model.dart:177)
			#2      replaceAllLinks (package:dartdoc/src/model_utils.dart:50)
			#3      ModelElement.resolveReferences (package:dartdoc/src/model.dart:181)
			#4      resolveDocReferences (package:dartdoc/src/html_generator.dart:569)
			#5      oneLiner (package:dartdoc/src/html_generator.dart:544)
			#6      _MustacheContext.callLambda (package:mustache4dart/mustache_context.dart:70)
			#7      _MustacheContext.call (package:mustache4dart/mustache_context.dart:64)
			#8      _StartSectionToken.apply (package:mustache4dart/src/tokens.dart:298)
			#9      Token.call (package:mustache4dart/src/tokens.dart:44)
			#10     _Template._write (package:mustache4dart/src/tmpl.dart:100)
			#11     _Template.call (package:mustache4dart/src/tmpl.dart:72)
			#12     render (package:mustache4dart/src/mustache.dart:10)
			#13     _PartialToken.apply (package:mustache4dart/src/tokens.dart:213)
			#14     _StartSectionToken.apply.<anonymous closure>.<anonymous closure> (package:mustache4dart/src/tokens.dart:290)
			#15     _StartSectionToken.forEachUntilEndSection (package:mustache4dart/src/tokens.dart:312)
			#16     _StartSectionToken.apply.<anonymous closure> (package:mustache4dart/src/tokens.dart:290)
			#17     Iterable.forEach (dart:core/iterable.dart:206)
			#18     _StartSectionToken.apply (package:mustache4dart/src/tokens.dart:289)
			#19     _StartSectionToken.apply.<anonymous closure> (package:mustache4dart/src/tokens.dart:302)
			#20     _StartSectionToken.forEachUntilEndSection (package:mustache4dart/src/tokens.dart:312)
			#21     _StartSectionToken.apply (package:mustache4dart/src/tokens.dart:302)
			#22     Token.call (package:mustache4dart/src/tokens.dart:44)

**Comment by sethladd** [comment]
Awesome, thanks for the report!

**Comment by sethladd** [comment]
Can you link to the package's location so we can try to reproduce?

**Comment by alan-knight** [comment]
https://github.com/dart-lang/intl

**Comment by keertip** [comment]
@alan-knight 

Cloned the repo and tried it out with the latest dartdoc, I am not able to repro the problem. I could generate the docs. Did you have any local changes?

**Comment by alan-knight** [comment]
I had one which was extremely minor, and I tried it again on master with the same issue. I did the global activate using my own built pub from bleeding edge, but that's the only difference I can think of.

**Comment by sethladd** [comment]
Ah. Let me push the latest version to pub. @keertip is probably using a version from master.

**Comment by keertip** [comment]
Ah, yes. Thanks!

**Comment by sethladd** [comment]
Done!

**Comment by sethladd** [comment]
Let me know if the version in pub.dartlang.org still crashes.

**Comment by alan-knight** [comment]
Yes, it does.

**Comment by keertip** [comment]
Ok, will install the published package and try it out.

**Comment by keertip** [comment]
Installed `dartdoc` via `pub global activate` and ran it on `intl`. Still see no crash, can generate docs.

**Comment by keertip** [comment]
@alan-knight, can you do a `dartdoc --version` to confirm you are running the latest version?

**Comment by alan-knight** [comment]
dartdoc version: 0.0.1+5

OK, it seems like there was something wrong with pub setup for that instance. Pub cache repair didn't help, but deleting all the packages directories and re-running fixed it.
