### ISSUE TITLE
Generation failed: The null object does not have a method 'replaceAll'.

### ISSUE THREAD

**Issue by Janamou** [dart-lang/dartdoc#702]
Today I updated to the latest dartdoc version (0.2.0) and when I run it on a simple project generated in WebStorm like this:
**New Project/Dart/Check generate sample content - SIMPLE command line application** and then try to run the dartdoc on it, I get this exception.

(It is really important to select the simple project template.)

I tried to create the `lib/` folder with some Dart script there but it outputs the same exception (after parsing 1 file in lib). 

```
Generating documentation for 'untitled' into /Users/janamou/Projects/untitled/doc/api/

Parsed 0 files in 0.2 seconds.

Generation failed: The null object does not have a method 'replaceAll'.

NoSuchMethodError: method not found: 'replaceAll'
Receiver: null
Arguments: ["\r\n", "\n"]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      markdownToHtml (package:markdown/src/html_renderer.dart:24:26)
#3      renderMarkdownToHtml (package:dartdoc/markdown_processor.dart:53:10)
#4      Package.documentationAsHtml (package:dartdoc/src/model.dart:382:37)
#5      _LocalInstanceMirror._invokeGetter (dart:mirrors-patch/mirrors_impl.dart:530)
#6      _LocalInstanceMirror._getFieldSlow (dart:mirrors-patch/mirrors_impl.dart:447)
#7      _LocalInstanceMirror.getField (dart:mirrors-patch/mirrors_impl.dart:461)
#8      _ObjectReflectorDeclaration.value (package:mustache4dart/mustache_context.dart:325:19)
#9      _ObjectReflector.[] (package:mustache4dart/mustache_context.dart:254:24)
#10     _MustacheContext._getActualValue (package:mustache4dart/mustache_context.dart:139:56)
#11     _MustacheContext._getMustachContext (package:mustache4dart/mustache_context.dart:110:13)
#12     _MustacheContext._getContextForKey (package:mustache4dart/mustache_context.dart:106:12)
#13     _MustacheContext._getInThisOrParent (package:mustache4dart/mustache_context.dart:79:18)
#14     _MustacheContext.[] (package:mustache4dart/mustache_context.dart:75:12)
#15     _ExpressionToken.apply (package:mustache4dart/src/tokens.dart:170:18)
#16     Token.call (package:mustache4dart/src/tokens.dart:44:18)
#17     _Template._write (package:mustache4dart/src/tmpl.dart:100:20)
#18     _Template.call (package:mustache4dart/src/tmpl.dart:72:5)
#19     render (package:mustache4dart/src/mustache.dart:10:20)
#20     _PartialToken.apply (package:mustache4dart/src/tokens.dart:213:16)
#21     _StartSectionToken.apply.<anonymous closure> (package:mustache4dart/src/tokens.dart:302:53)
#22     _StartSectionToken.forEachUntilEndSection (package:mustache4dart/src/tokens.dart:312:8)
#23     _StartSectionToken.apply (package:mustache4dart/src/tokens.dart:302:5)
#24     Token.call (package:mustache4dart/src/tokens.dart:44:18)
#25     _Template._write (package:mustache4dart/src/tmpl.dart:100:20)
#26     _Template.call (package:mustache4dart/src/tmpl.dart:72:5)
#27     HtmlGeneratorInstance._build (package:dartdoc/src/html_generator.dart:539:30)
#28     HtmlGeneratorInstance.generatePackage (package:dartdoc/src/html_generator.dart:240:5)
#29     HtmlGeneratorInstance.generate.<generate_async_body> (package:dartdoc/src/html_generator.dart:153:5)
#30     _RootZone.runUnary (dart:async/zone.dart:1166)
#31     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#32     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#33     _Future._completeWithValue (dart:async/future_impl.dart:368)
#34     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#36     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

I have this problem only with this "simple" project (larger command line application works and also my projects work).

**Comment by Janamou** [comment]
I ran it on the same project yesterday with older version and it worked normally.

**Comment by devoncarew** [comment]
Possibly fixed by https://github.com/dart-lang/dartdoc/pull/701; it addresses a regression w/ `null` docs.

**Comment by sethladd** [comment]
Are we missing a test case for this situation? (sorry you ran into this :(

**Comment by devoncarew** [comment]
Fixed; @Janamou, can you re-test after the next push to pub? Thanks!

**Comment by Janamou** [comment]
@devoncarew sure, I will test it :)

**Comment by devoncarew** [comment]
`0.2.1` has been published :)

**Comment by sethladd** [comment]
Thanks for the report, and thanks for the quick fix :)

**Comment by Janamou** [comment]
@devoncarew @sethladd I tried it and it didn't solve the problem. The reason is really funny:
the project has to include *README.md*, without it the docgen throws this exception (you are using it on the first page of documentation).

The simple console app project from WebStorm doesn't include README.md :-D

**Comment by sethladd** [comment]
Yikes, thanks for pointing this out. dartdoc should work, even if a readme.md isn't found. Can you please open an issue for us?
